In [4]:
import torch
import torchvision
import torchvision.transforms as transforms
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim
import torch
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

transform = transforms.Compose(
    [transforms.Resize(224),
     transforms.CenterCrop(224),
     transforms.ToTensor(),
     transforms.Normalize((0.5, 0.5, 0.5), (0.5, 0.5, 0.5))])

trainset = torchvision.datasets.ImageFolder(root='./cars_train', transform=transform)
trainloader = torch.utils.data.DataLoader(trainset, batch_size=1, shuffle=True, num_workers=2)

testset = torchvision.datasets.ImageFolder(root='./cars_test', transform=transform)
testloader = torch.utils.data.DataLoader(testset, batch_size=3, shuffle=False, num_workers=2)



for images, labels in trainloader:
    print(images.shape)
    print(labels)

torch.Size([1, 3, 224, 224])
tensor([0])
torch.Size([1, 3, 224, 224])
tensor([0])
torch.Size([1, 3, 224, 224])
tensor([0])
torch.Size([1, 3, 224, 224])
tensor([0])
torch.Size([1, 3, 224, 224])
tensor([0])
torch.Size([1, 3, 224, 224])
tensor([0])
torch.Size([1, 3, 224, 224])
tensor([0])
torch.Size([1, 3, 224, 224])
tensor([0])
torch.Size([1, 3, 224, 224])
tensor([0])
torch.Size([1, 3, 224, 224])
tensor([0])
torch.Size([1, 3, 224, 224])
tensor([0])
torch.Size([1, 3, 224, 224])
tensor([0])
torch.Size([1, 3, 224, 224])
tensor([0])
torch.Size([1, 3, 224, 224])
tensor([0])
torch.Size([1, 3, 224, 224])
tensor([0])
torch.Size([1, 3, 224, 224])
tensor([0])
torch.Size([1, 3, 224, 224])
tensor([0])
torch.Size([1, 3, 224, 224])
tensor([0])
torch.Size([1, 3, 224, 224])
tensor([0])
torch.Size([1, 3, 224, 224])
tensor([0])
torch.Size([1, 3, 224, 224])
tensor([0])
torch.Size([1, 3, 224, 224])
tensor([0])
torch.Size([1, 3, 224, 224])
tensor([0])
torch.Size([1, 3, 224, 224])
tensor([0])
torch.Size([1, 3

In [2]:
# Create the MLP model class
import torch.nn as nn
import torch.nn.functional as F

## Define the NN architecture
class Net(nn.Module):
    def __init__(self):
        super(Net, self).__init__()
        self.fc1 = nn.Linear(150528, 512)
        # linear layer (n_hidden -> hidden_2)
        self.fc2 = nn.Linear(512, 512)
        # linear layer (n_hidden -> 10)
        self.fc3 = nn.Linear(512, 10)
        # dropout layer (p=0.2)
        # dropout prevents overfitting of data
        self.dropout = nn.Dropout(0.5)

    def forward(self, x):
        # flatten image input
        x = x.view(-1,150528)
        # add hidden layer, with relu activation function
        x = F.relu(self.fc1(x))
        return x

# initialize the NN
model = Net().to(device)
print(model)

Net(
  (fc1): Linear(in_features=150528, out_features=512, bias=True)
  (fc2): Linear(in_features=512, out_features=512, bias=True)
  (fc3): Linear(in_features=512, out_features=10, bias=True)
  (dropout): Dropout(p=0.5, inplace=False)
)


In [3]:

criterion = nn.CrossEntropyLoss()

# specify optimizer
optimizer = torch.optim.SGD(model.parameters(), lr=0.01)

In [6]:


for epoch in range(10):
    running_loss = 0.0
    for i, data in enumerate(trainloader, 0):
        
        
        inputs, labels = data[0].to(device), data[1].to(device)
       
        
        optimizer.zero_grad()
        
        outputs = model(inputs)
        loss = criterion(outputs, labels)
        loss.backward()
        optimizer.step()

        running_loss += loss.item()
    print('Epoch %d loss: %.3f' % (epoch + 1, running_loss / len(trainloader)))

print('Finished Training')

Epoch 1 loss: 2.696
Epoch 2 loss: 2.078
Epoch 3 loss: 2.188
Epoch 4 loss: 1.935
Epoch 5 loss: 1.844
Epoch 6 loss: 1.612
Epoch 7 loss: 1.790
Epoch 8 loss: 1.609
Epoch 9 loss: 1.642
Epoch 10 loss: 1.504
Finished Training


In [7]:
correct = 0
total = 0
with torch.no_grad():
    for data in testloader:
        images, labels = data[0].to(device), data[1].to(device)
        outputs = model(images)
        _, predicted = torch.max(outputs.data, 1)
        total += labels.size(0)
        correct += (predicted == labels).sum().item()

print('Accuracy of the model on the test images: %d %%' % (100 * correct / total))

Accuracy of the model on the test images: 97 %
